# Generated by Django 4.0.1 on 2024-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vehiclelisting_condition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='owner_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
