# Generated by Django 4.0.1 on 2024-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='additional_image4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
