# Generated by Django 4.0.1 on 2024-05-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vehiclelisting_insurance_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_peripherals', models.TextField()),
                ('drivetrain', models.TextField()),
                ('body_structure_chassis', models.TextField()),
                ('exterior', models.TextField()),
                ('interior', models.TextField()),
                ('mechanical', models.TextField()),
                ('wheels_tyres', models.TextField()),
                ('vehicle_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='users.vehiclelisting')),
            ],
        ),
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_arai', models.CharField(max_length=50)),
                ('boot_space', models.CharField(max_length=50)),
                ('ground_clearance', models.CharField(max_length=50)),
                ('seating_capacity', models.CharField(max_length=50)),
                ('fuel_tank_capacity', models.CharField(max_length=50)),
                ('displacement', models.CharField(max_length=50)),
                ('vehicle_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_spec', to='users.vehiclelisting')),
            ],
        ),
    ]
