# Generated by Django 4.0.1 on 2024-05-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_inspectionreport_carspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='insurance_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='insurance_validity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='num_owners',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='registration_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='rto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='seller_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='transmission',
            field=models.CharField(max_length=50),
        ),
    ]
