# Generated by Django 4.0.1 on 2024-05-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_vehiclelisting_insurance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='full_details',
            field=models.FileField(blank=True, null=True, upload_to='full_details/'),
        ),
    ]
