# Generated by Django 4.0.1 on 2024-05-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_vehiclelisting_full_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_arai', models.CharField(max_length=100)),
                ('boot_space', models.CharField(max_length=100)),
                ('ground_clearance', models.CharField(max_length=100)),
                ('seating_capacity', models.CharField(max_length=100)),
                ('fuel_tank_capacity', models.CharField(max_length=100)),
                ('displacement', models.CharField(max_length=100)),
                ('engine_peripherals', models.CharField(max_length=100)),
                ('drivetrain', models.CharField(max_length=100)),
                ('body_structure', models.CharField(max_length=100)),
                ('exterior', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('mechanical', models.CharField(max_length=100)),
                ('wheels_tyres', models.CharField(max_length=100)),
                ('vehicle_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='users.vehiclelisting')),
            ],
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='vehicle_listing',
        ),
        migrations.DeleteModel(
            name='CarSpecification',
        ),
        migrations.DeleteModel(
            name='InspectionReport',
        ),
    ]
