# Generated by Django 4.0.1 on 2024-05-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_saveddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_ara', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boot_space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ground_clearance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seating_capacity', models.IntegerField()),
                ('fuel_tank_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('displacement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine_peripherals', models.TextField()),
                ('drivetrain', models.TextField()),
                ('body_structure_chassis', models.TextField()),
                ('exterior', models.TextField()),
                ('interior', models.TextField()),
                ('mechanical', models.TextField()),
                ('wheels_tyres', models.TextField()),
                ('full_details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='saveddetails',
            name='vehicle_listing',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='SavedDetails',
        ),
    ]
