# Generated by Django 4.0.1 on 2024-05-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cardetails_is_approved_cardetails_owner_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='owner_review',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='star_rating',
        ),
    ]
