# Generated by Django 4.0.1 on 2024-05-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_cardetails_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
