# Generated by Django 4.0.1 on 2024-05-24 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_cardetails_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='vehicle_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehiclelisting'),
        ),
    ]
