# Generated by Django 4.0.1 on 2024-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_cardetails_vehicle_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='owner_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='star_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
